#!/usr/bin/env python3
"""Deprecated V12d helper.

Comparison appendix slides 23-25 are now generated by
scripts/build_evaluation_slides.py after the normalized Gemma 4 comparison
artifact is created.
"""

from __future__ import annotations


def main() -> int:
    print(
        "This helper is superseded. Run "
        "scripts/extract_gemma4_rag_norag_comparison.py, then "
        "scripts/build_evaluation_slides.py."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
