"""
RAG Pipeline Configuration
Loads credentials from .env and defines model paths
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
ENV_PATH = Path(__file__).parent.parent.parent / ".env"
load_dotenv(ENV_PATH)

# =============================================================================
# API Credentials
# =============================================================================
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
QDRANT_URL = os.getenv("QDRANT_URL")

# Validate required keys
if not QDRANT_API_KEY or not QDRANT_URL:
    raise ValueError("QDRANT_API_KEY and QDRANT_URL must be set in .env")
if not GOOGLE_API_KEY:
    raise ValueError("GOOGLE_API_KEY must be set in .env")

# =============================================================================
# Model Paths (Local HuggingFace Cache)
# =============================================================================
HF_CACHE = Path("/data4t/hf/transformers")

MODELS = {
    # Lane 1: Text IR
    "e5_large": HF_CACHE / "models--intfloat--multilingual-e5-large-instruct",
    "medcpt_query": HF_CACHE / "MedCPT-Query-Encoder",
    "medcpt_cross": HF_CACHE / "MedCPT-Cross-Encoder",
    # Lane 2: Vision-Language (needs download)
    "biomedclip": "microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224",
    # Generation
    "medgemma": HF_CACHE / "models--google--medgemma-4b-it",
}

# =============================================================================
# Qdrant Collections - Explicit Dimension Naming per GPT 5.2 Feedback
# =============================================================================
# Dataset version for reproducibility (GPT 5.2 checkpoint #1)
DATASET_VERSION = "v143"  # verified_143: 114 train + 29 test

COLLECTIONS = {
    # Lane 1: Text retrieval (E5 = 1024d) - Versioned per GPT 5.2 #2
    f"cases_text_e5_1024_{DATASET_VERSION}": {"dim": 1024, "distance": "Cosine", "encoder": "E5"},
    f"cases_text_bm25_{DATASET_VERSION}": {"type": "sparse"},  # BM25 index
    
    # Lane 2: Vision-Language (BiomedCLIP = 512d) - Versioned
    f"captions_biomedclip_512_{DATASET_VERSION}": {"dim": 512, "distance": "Cosine", "encoder": "BiomedCLIP"},
    f"images_biomedclip_512_{DATASET_VERSION}": {"dim": 512, "distance": "Cosine", "encoder": "BiomedCLIP"},
    
    # Legacy collection names (for backward compatibility with existing runs)
    "cases_text_e5_1024": {"dim": 1024, "distance": "Cosine", "encoder": "E5"},
    "captions_biomedclip_512": {"dim": 512, "distance": "Cosine", "encoder": "BiomedCLIP"},
    "images_biomedclip_512": {"dim": 512, "distance": "Cosine", "encoder": "BiomedCLIP"},
}


# =============================================================================
# Data Paths
# =============================================================================
# DATA_ROOT: Legacy multimodal dataset (406 cases) - ONLY for images and legacy files
DATA_ROOT = Path(__file__).parent.parent.parent / "data" / "leishmaniasis_multimodal"

# Split files: 143 verified Leishmaniasis cases with article-based splitting
# (114 train / 29 test, no article overlap, anti-leakage verified)
SPLIT_DIR = Path(__file__).parent.parent.parent / "data" / "leishmaniasis_verified"
TRAIN_JSONL = SPLIT_DIR / "train.jsonl"  # 114 cases
TEST_JSONL = SPLIT_DIR / "test.jsonl"    # 29 cases

# Legacy paths (for reference only - DO NOT USE for new experiments)
_SPLIT_DIR_OLD = Path(__file__).parent.parent.parent / "data" / "leishmaniasis_split"  # 183/45
_TRAIN_JSONL_OLD = DATA_ROOT / "train_clean.jsonl"   # Old 350/56 split
_TEST_JSONL_OLD = DATA_ROOT / "test_clean.jsonl"     # Old 350/56 split


# Entity links filtered to verified cases (generated by filter_entity_links.py)
ENTITY_LINKS = SPLIT_DIR / "case_entity_links.jsonl"
# Images remain in DATA_ROOT (not duplicated)
IMAGES_DIR = DATA_ROOT / "images"

# =============================================================================
# Chunking Parameters
# =============================================================================
CHUNK_CONFIG = {
    "max_tokens": 400,
    "overlap_tokens": 50,
    "strategies": ["fixed", "section", "semantic"],
}

# =============================================================================
# Evaluation Parameters
# =============================================================================
EVAL_CONFIG = {
    "k_values": [5, 10],
    "query_types": ["symptom_only", "symptom_exposure", "image_only"],
}

# =============================================================================
# LLM Judge (Gemini 2.5 Pro for RAGAs)
# =============================================================================
# Use stable model ID (GA June 2025), not preview
JUDGE_MODEL = "gemini-2.5-pro"  # Stable, vision-capable for Multimodal Faithfulness
JUDGE_MODEL_FALLBACK = "gemini-1.5-pro"  # Fallback if 2.5 unavailable
JUDGE_CONFIG = {
    "temperature": 0,
    "thinking_budget": 1024,  # Low for eval tasks per Gemini docs
    "max_retries": 3,
    "retry_delay": 2,
}

# =============================================================================
# Generation Models (per user request: use gemini-2.5-pro, add medgemma)
# =============================================================================
GENERATOR_MODEL = "gemini-2.5-pro"  # Primary (not flash preview)
GENERATOR_MODEL_MEDGEMMA = "google/medgemma-4b-it"  # Local experiment

# =============================================================================
# Runs Directory
# =============================================================================
RUNS_DIR = Path(__file__).parent.parent / "runs"


# =============================================================================
# Environment Summary (for reproducibility logging)
# =============================================================================
def log_env_summary() -> None:
    """Print environment configuration for reproducibility."""
    print("=" * 60)
    print("ENVIRONMENT SUMMARY")
    print("=" * 60)
    print(f"  HF_HOME:                  {os.environ.get('HF_HOME', 'NOT SET')}")
    print(f"  TRANSFORMERS_CACHE:       {os.environ.get('TRANSFORMERS_CACHE', 'NOT SET')}")
    print(f"  SENTENCE_TRANSFORMERS_HOME: {os.environ.get('SENTENCE_TRANSFORMERS_HOME', 'NOT SET')}")
    print(f"  DATA_ROOT:                {DATA_ROOT}")
    print(f"  QDRANT_URL:               {QDRANT_URL}")
    print("=" * 60)
