"""
Build phase-specific train variants by appending selected non-leish cases.

This script creates versioned outputs without overwriting baseline files:
- train_<phase>.jsonl
- train_pseudolabel_v2_<phase>.jsonl
- merge_validation_<phase>.json

The source cases come from case_records generated by the medgemma27/qwen32
pseudo-labeling workflow.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

from .chunker import estimate_tokens


CASE_ID_RE = re.compile(r"^PMC\d+_\d+$")
CASE_TEXT_MAX_TOKENS = 700
NARRATIVE_MIN_COMPLETE_TOKENS = 80
FIXED_CHUNK_MAX_TOKENS = 400
FIXED_CHUNK_OVERLAP_TOKENS = 50


@dataclass
class MergeStats:
    phase_name: str
    requested_case_count: int
    unique_requested_case_count: int
    added_case_count: int
    missing_case_count: int
    collision_train_count: int
    collision_test_count: int


@dataclass
class CaseTextBuildResult:
    text: str
    sections: List[str]
    estimated_tokens: int


def parse_maybe_list(value: Any) -> List[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v).strip() for v in value if str(v).strip()]
    text = str(value).strip()
    if not text:
        return []
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        return [text]
    if isinstance(parsed, list):
        return [str(v).strip() for v in parsed if str(v).strip()]
    if parsed is None:
        return []
    return [str(parsed).strip()]


def is_empty_value(value: Any) -> bool:
    return value in (None, "", [], {})


def merge_non_empty_fields(preferred: Dict[str, Any], fallback: Dict[str, Any]) -> Dict[str, Any]:
    """Merge two records preferring non-empty values from preferred."""
    merged = dict(fallback or {})
    for key, value in (preferred or {}).items():
        if not is_empty_value(value):
            merged[key] = value
    return merged


def read_jsonl(path: Path) -> List[Dict]:
    rows: List[Dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def write_jsonl(path: Path, rows: Iterable[Dict]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
            count += 1
    return count


def read_case_ids(path: Path) -> List[str]:
    ordered: List[str] = []
    seen = set()
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            cid = raw.strip()
            if not cid:
                continue
            cid = cid.upper()
            if not CASE_ID_RE.match(cid):
                raise ValueError(f"Invalid case_id in list: {cid}")
            if cid not in seen:
                seen.add(cid)
                ordered.append(cid)
    return ordered


def parse_tagged(xml_like_text: str, tag_name: str) -> str:
    if not xml_like_text:
        return ""
    pattern = rf"<{re.escape(tag_name)}>(.*?)</{re.escape(tag_name)}>"
    match = re.search(pattern, xml_like_text, flags=re.IGNORECASE | re.DOTALL)
    return match.group(1).strip() if match else ""


def normalize_dx_name(value: str) -> str:
    text = (value or "").strip()
    if not text:
        return "Non-Leishmaniasis"
    if text.upper() == "NO_MATCH":
        return "Non-Leishmaniasis"
    return text


def build_diag_name(case_record: Dict) -> str:
    candidates = [
        case_record.get("primary_disease_mapped", ""),
        case_record.get("primary_diagnosis_text", ""),
        case_record.get("prompt1_final_diagnosis_mapped", ""),
        case_record.get("prompt1_final_diagnosis", ""),
    ]
    matched = case_record.get("matched_disease_candidates") or []
    if matched:
        candidates.append(str(matched[0]))

    for candidate in candidates:
        normalized = normalize_dx_name(str(candidate))
        if normalized and normalized != "Non-Leishmaniasis":
            return normalized

    for candidate in candidates:
        normalized = normalize_dx_name(str(candidate))
        if normalized:
            return normalized

    return "Non-Leishmaniasis"


def _normalize_text_block(value: Any) -> str:
    text = str(value or "").strip()
    if not text or text.lower() == "nan":
        return ""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _normalize_sentence_spacing(text: str) -> str:
    return re.sub(r"\s+", " ", (text or "").strip())


def _split_sentences(text: str) -> List[str]:
    normalized = _normalize_text_block(text)
    if not normalized:
        return []
    return [part.strip() for part in re.split(r"(?<=[.!?])\s+", normalized) if part.strip()]


def _trim_words_to_tokens(text: str, max_tokens: int) -> str:
    normalized = _normalize_text_block(text)
    if not normalized or max_tokens <= 0:
        return ""
    max_words = max(1, int(max_tokens / 1.3))
    return " ".join(normalized.split()[:max_words]).strip()


def _trim_to_sentence_budget(text: str, max_tokens: int) -> str:
    normalized = _normalize_text_block(text)
    if not normalized or max_tokens <= 0:
        return ""
    if estimate_tokens(normalized) <= max_tokens:
        return normalized

    selected: List[str] = []
    for sentence in _split_sentences(normalized):
        candidate = " ".join(selected + [sentence]).strip()
        if selected and estimate_tokens(candidate) > max_tokens:
            break
        if not selected and estimate_tokens(sentence) > max_tokens:
            return _trim_words_to_tokens(sentence, max_tokens)
        selected.append(sentence)

    if selected:
        return " ".join(selected).strip()
    return _trim_words_to_tokens(normalized, max_tokens)


def _dedupe_section_texts(values: Iterable[str]) -> List[str]:
    unique_values: List[str] = []
    seen = set()
    for value in values:
        normalized = _normalize_sentence_spacing(value).lower()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        unique_values.append(_normalize_text_block(value))
    return unique_values


def _render_section(label: str, body: str) -> str:
    body = _normalize_text_block(body)
    if not body:
        return ""
    return f"{label}:\n{body}"


def _extract_prompt_fallback(case_record: Dict) -> str:
    prompt2_quality_pass = bool(case_record.get("prompt2_quality_pass", False))
    values = [
        case_record.get("prompt2_case_prompt", "") if prompt2_quality_pass else "",
        case_record.get("prompt1_case_prompt", ""),
        parse_tagged(case_record.get("prompt1_response_raw", ""), "case_prompt"),
    ]
    for value in values:
        text = _normalize_text_block(value)
        if text:
            return text
    return ""


def _build_reference_diagnosis(case_record: Dict) -> str:
    diagnosis = build_diag_name(case_record)
    diagnosis_type = str(case_record.get("diagnosis_type") or "Non-Leishmaniasis").strip() or "Non-Leishmaniasis"
    reference = [f"Diagnosis: {diagnosis}.", f"Diagnosis Type: {diagnosis_type}."]
    species = _normalize_text_block(case_record.get("species"))
    if species:
        reference.append(f"Species: {species}.")
    return " ".join(reference)


def _compose_case_sections(case_record: Dict, source_case: Dict) -> List[Tuple[str, str]]:
    source_narrative = _normalize_text_block(source_case.get("case_text"))
    source_abstract = _normalize_text_block(source_case.get("abstract"))
    structured_case_text = _normalize_text_block(case_record.get("case_text"))
    structured_abstract = _normalize_text_block(case_record.get("abstract"))
    evidence = _normalize_text_block(case_record.get("evidence"))
    rationale = _normalize_text_block(case_record.get("rationale"))
    fallback_prompt = _extract_prompt_fallback(case_record)

    narrative_parts: List[str] = []
    if source_narrative:
        narrative_parts.append(source_narrative)
    elif structured_case_text:
        narrative_parts.append(structured_case_text)
    if source_abstract and (
        not narrative_parts or estimate_tokens("\n\n".join(narrative_parts)) < NARRATIVE_MIN_COMPLETE_TOKENS
    ):
        narrative_parts.append(source_abstract)
    elif structured_abstract and (
        not narrative_parts or estimate_tokens("\n\n".join(narrative_parts)) < NARRATIVE_MIN_COMPLETE_TOKENS
    ):
        narrative_parts.append(structured_abstract)

    narrative = "\n\n".join(_dedupe_section_texts(narrative_parts))
    if not narrative and fallback_prompt:
        narrative = fallback_prompt

    sections: List[Tuple[str, str]] = []
    if narrative:
        sections.append(("Clinical Narrative", narrative))
    if evidence:
        sections.append(("Key Diagnostic Evidence", evidence))
    if rationale:
        sections.append(("Reasoning Summary", rationale))

    reference_diagnosis = _build_reference_diagnosis(case_record)
    if reference_diagnosis:
        sections.append(("Reference Diagnosis", reference_diagnosis))
    return sections


def _trim_case_sections(sections: List[Tuple[str, str]], max_tokens: int = CASE_TEXT_MAX_TOKENS) -> CaseTextBuildResult:
    lookup = {label: _normalize_text_block(body) for label, body in sections if _normalize_text_block(body)}
    narrative = lookup.get("Clinical Narrative", "")
    evidence = lookup.get("Key Diagnostic Evidence", "")
    reasoning = lookup.get("Reasoning Summary", "")
    reference = lookup.get("Reference Diagnosis", "")

    mandatory_sections: List[Tuple[str, str]] = []
    if evidence:
        mandatory_sections.append(("Key Diagnostic Evidence", evidence))
    if reference:
        mandatory_sections.append(("Reference Diagnosis", reference))

    mandatory_text = "\n\n".join(_render_section(label, body) for label, body in mandatory_sections if body)
    mandatory_tokens = estimate_tokens(mandatory_text) if mandatory_text else 0

    if mandatory_tokens > max_tokens:
        reference_tokens = estimate_tokens(_render_section("Reference Diagnosis", reference)) if reference else 0
        evidence_budget = max(max_tokens - reference_tokens - 8, 0)
        trimmed_evidence = _trim_to_sentence_budget(evidence, evidence_budget)
        mandatory_sections = []
        if trimmed_evidence:
            mandatory_sections.append(("Key Diagnostic Evidence", trimmed_evidence))
        if reference:
            mandatory_sections.append(("Reference Diagnosis", reference))
        mandatory_text = "\n\n".join(_render_section(label, body) for label, body in mandatory_sections if body)
        mandatory_tokens = estimate_tokens(mandatory_text) if mandatory_text else 0

    remaining_budget = max(max_tokens - mandatory_tokens, 0)
    trimmed_narrative = ""
    trimmed_reasoning = ""
    if narrative and remaining_budget > 0:
        narrative_budget = remaining_budget
        if reasoning:
            reasoning_reserve = min(max(estimate_tokens(reasoning), 40), max(remaining_budget // 3, 40))
            narrative_budget = max(remaining_budget - reasoning_reserve, remaining_budget // 2)
        trimmed_narrative = _trim_to_sentence_budget(narrative, narrative_budget)
        remaining_budget = max(remaining_budget - estimate_tokens(trimmed_narrative), 0)
    if reasoning and remaining_budget > 0:
        trimmed_reasoning = _trim_to_sentence_budget(reasoning, remaining_budget)

    selected_sections: List[Tuple[str, str]] = []
    for label, body in [
        ("Clinical Narrative", trimmed_narrative),
        ("Key Diagnostic Evidence", dict(mandatory_sections).get("Key Diagnostic Evidence", "")),
        ("Reasoning Summary", trimmed_reasoning),
        ("Reference Diagnosis", dict(mandatory_sections).get("Reference Diagnosis", "")),
    ]:
        body = _normalize_text_block(body)
        if body:
            selected_sections.append((label, body))

    rendered = "\n\n".join(
        _render_section(label, body)
        for label, body in selected_sections
        if _render_section(label, body)
    ).strip()

    if estimate_tokens(rendered) > max_tokens:
        overflow = estimate_tokens(rendered) - max_tokens
        if trimmed_reasoning:
            reasoning_budget = max(estimate_tokens(trimmed_reasoning) - overflow - 4, 0)
            trimmed_reasoning = _trim_to_sentence_budget(trimmed_reasoning, reasoning_budget)
        selected_sections = []
        for label, body in [
            ("Clinical Narrative", trimmed_narrative),
            ("Key Diagnostic Evidence", dict(mandatory_sections).get("Key Diagnostic Evidence", "")),
            ("Reasoning Summary", trimmed_reasoning),
            ("Reference Diagnosis", dict(mandatory_sections).get("Reference Diagnosis", "")),
        ]:
            body = _normalize_text_block(body)
            if body:
                selected_sections.append((label, body))
        rendered = "\n\n".join(
            _render_section(label, body)
            for label, body in selected_sections
            if _render_section(label, body)
        ).strip()

    if estimate_tokens(rendered) > max_tokens and trimmed_narrative:
        overflow = estimate_tokens(rendered) - max_tokens
        narrative_budget = max(estimate_tokens(trimmed_narrative) - overflow - 4, 0)
        trimmed_narrative = _trim_to_sentence_budget(trimmed_narrative, narrative_budget)
        selected_sections = []
        for label, body in [
            ("Clinical Narrative", trimmed_narrative),
            ("Key Diagnostic Evidence", dict(mandatory_sections).get("Key Diagnostic Evidence", "")),
            ("Reasoning Summary", trimmed_reasoning),
            ("Reference Diagnosis", dict(mandatory_sections).get("Reference Diagnosis", "")),
        ]:
            body = _normalize_text_block(body)
            if body:
                selected_sections.append((label, body))
        rendered = "\n\n".join(
            _render_section(label, body)
            for label, body in selected_sections
            if _render_section(label, body)
        ).strip()

    max_words_for_two_chunks = int(
        (FIXED_CHUNK_MAX_TOKENS / 1.3) + ((FIXED_CHUNK_MAX_TOKENS - FIXED_CHUNK_OVERLAP_TOKENS) / 1.3)
    )
    words = rendered.split()
    if len(words) > max_words_for_two_chunks:
        safe_word_budget = max_words_for_two_chunks
        trimmed_narrative = _trim_words_to_tokens(trimmed_narrative, max(int(safe_word_budget * 1.3), 0))
        selected_sections = []
        for label, body in [
            ("Clinical Narrative", trimmed_narrative),
            ("Key Diagnostic Evidence", dict(mandatory_sections).get("Key Diagnostic Evidence", "")),
            ("Reasoning Summary", trimmed_reasoning),
            ("Reference Diagnosis", dict(mandatory_sections).get("Reference Diagnosis", "")),
        ]:
            body = _normalize_text_block(body)
            if body:
                selected_sections.append((label, body))
        rendered = "\n\n".join(
            _render_section(label, body)
            for label, body in selected_sections
            if _render_section(label, body)
        ).strip()

    return CaseTextBuildResult(
        text=rendered,
        sections=[label for label, _ in selected_sections],
        estimated_tokens=estimate_tokens(rendered),
    )


def build_case_text(case_record: Dict, source_case: Dict) -> CaseTextBuildResult:
    return _trim_case_sections(_compose_case_sections(case_record, source_case))


def load_source_candidates(path: Path) -> Dict[str, Dict]:
    if not path.exists():
        raise FileNotFoundError(f"Source candidates JSONL not found: {path}")

    rows_by_case: Dict[str, Dict] = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            case_id = str(row.get("case_id", "")).upper()
            if case_id:
                rows_by_case[case_id] = row
    return rows_by_case


def load_classified_cases(path: Path) -> Dict[str, Dict]:
    if not path.exists():
        raise FileNotFoundError(f"classified_cases JSONL not found: {path}")

    rows_by_case: Dict[str, Dict] = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            case_id = str(row.get("case_id", "")).upper()
            if case_id:
                rows_by_case[case_id] = row
    return rows_by_case


def load_image_inventory(path: Path) -> Tuple[Dict[str, List[Dict[str, str]]], Dict[str, List[Dict[str, str]]]]:
    if not path.exists():
        raise FileNotFoundError(f"Image inventory CSV not found: {path}")

    import csv

    by_case_id: Dict[str, List[Dict[str, str]]] = {}
    by_article_id: Dict[str, List[Dict[str, str]]] = {}
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            case_id = str(row.get("case_id", "")).upper()
            article_id = str(row.get("article_id", "")).upper()
            if case_id:
                by_case_id.setdefault(case_id, []).append(row)
            if article_id:
                by_article_id.setdefault(article_id, []).append(row)

    return by_case_id, by_article_id


def resolve_inventory_local_path(raw_path: str, aligned_images_root: Path, inv_case_id: str, resolved_file: str) -> Optional[Path]:
    if raw_path:
        candidate = Path(raw_path)
        if candidate.exists():
            return candidate

        legacy_prefix = "/data1t/lab/ngocnt/Leishmania_v3"
        home_prefix = "/home/ngocnt/Leishmania_v3"
        text = str(candidate)
        if text.startswith(legacy_prefix):
            rewritten = Path(home_prefix + text[len(legacy_prefix):])
            if rewritten.exists():
                return rewritten

    if inv_case_id and resolved_file:
        fallback = aligned_images_root / inv_case_id / resolved_file
        if fallback.exists():
            return fallback

    return None


def build_images_from_source(
    *,
    case_id: str,
    article_id: str,
    source_case: Dict,
    inventory_by_case_id: Dict[str, List[Dict[str, str]]],
    inventory_by_article_id: Dict[str, List[Dict[str, str]]],
    aligned_images_root: Path,
    materialize_images: bool,
    images_target_root: Path,
) -> Tuple[List[Dict[str, str]], List[str], Dict[str, Any]]:
    requested_files = parse_maybe_list(source_case.get("case_image_files"))
    requested_captions = parse_maybe_list(source_case.get("case_image_captions"))
    caption_by_requested = {
        requested_files[i]: requested_captions[i]
        for i in range(min(len(requested_files), len(requested_captions)))
        if requested_files[i]
    }

    rows = list(inventory_by_case_id.get(case_id, []))
    fallback_article_used = False
    if not rows and article_id in inventory_by_article_id and requested_files:
        candidate_rows = inventory_by_article_id[article_id]
        filtered = [r for r in candidate_rows if str(r.get("requested_file", "")) in set(requested_files)]
        if filtered:
            rows = filtered
            fallback_article_used = True

    images: List[Dict[str, str]] = []
    query_paths: List[str] = []
    seen_files = set()

    rows_by_requested_file: Dict[str, Dict[str, str]] = {}
    for row in rows:
        requested_file = str(row.get("requested_file", "")).strip()
        if requested_file and requested_file not in rows_by_requested_file:
            rows_by_requested_file[requested_file] = row

    unresolved_requested_files: List[str] = []

    # Preserve source-provided image file names/captions as-is when available.
    if requested_files:
        for requested_file in requested_files:
            if not requested_file or requested_file in seen_files:
                continue
            seen_files.add(requested_file)

            caption = caption_by_requested.get(requested_file, "")
            images.append({"file": requested_file, "caption": caption})

            row = rows_by_requested_file.get(requested_file)
            resolved_path = None
            if row is not None:
                inv_case_id = str(row.get("case_id", "")).upper()
                resolved_path = resolve_inventory_local_path(
                    str(row.get("local_path", "")).strip(),
                    aligned_images_root,
                    inv_case_id,
                    str(row.get("resolved_file", "")).strip(),
                )

            if materialize_images:
                if resolved_path is None:
                    unresolved_requested_files.append(requested_file)
                else:
                    target_dir = images_target_root / case_id
                    target_dir.mkdir(parents=True, exist_ok=True)
                    target_path = target_dir / requested_file
                    if not target_path.exists():
                        try:
                            target_path.symlink_to(resolved_path)
                        except OSError:
                            shutil.copy2(resolved_path, target_path)
                    query_paths.append(str(target_path))

    # If source did not provide explicit files, fallback to inventory rows.
    if not requested_files:
        for row in rows:
            inv_case_id = str(row.get("case_id", "")).upper()
            requested_file = str(row.get("requested_file", "")).strip()
            resolved_file = str(row.get("resolved_file", "")).strip()
            resolved_path = resolve_inventory_local_path(
                str(row.get("local_path", "")).strip(),
                aligned_images_root,
                inv_case_id,
                resolved_file,
            )
            if resolved_path is None:
                continue

            file_name = requested_file or resolved_path.name
            if file_name in seen_files:
                continue
            seen_files.add(file_name)

            caption = str(row.get("caption", "")).strip()
            images.append({"file": file_name, "caption": caption})

            if materialize_images:
                target_dir = images_target_root / case_id
                target_dir.mkdir(parents=True, exist_ok=True)
                target_path = target_dir / file_name
                if not target_path.exists():
                    try:
                        target_path.symlink_to(resolved_path)
                    except OSError:
                        shutil.copy2(resolved_path, target_path)
                query_paths.append(str(target_path))

    missing_requested_files = sorted(
        set(requested_files) - {str(r.get("requested_file", "")).strip() for r in rows}
    )
    audit = {
        "source_image_count": int(source_case.get("image_count", 0) or 0),
        "requested_file_count": len(requested_files),
        "inventory_rows_case_id": len(inventory_by_case_id.get(case_id, [])),
        "inventory_rows_article_id": len(inventory_by_article_id.get(article_id, [])),
        "fallback_article_used": fallback_article_used,
        "linked_image_count": len(images),
        "materialized_image_count": len(query_paths),
        "unresolved_requested_file_count": len(unresolved_requested_files),
        "unresolved_requested_files": unresolved_requested_files,
        "missing_requested_files": missing_requested_files,
    }
    return images, query_paths, audit


def extract_source_image_metadata(source_case: Dict) -> Dict[str, Any]:
    """Keep raw source image metadata fields when present for traceability."""
    metadata: Dict[str, Any] = {}

    list_fields = [
        "case_image_files",
        "case_image_captions",
        "image_paths",
        "image_filenames",
        "figure_refs",
        "figure_references",
        "image_modalities",
    ]
    scalar_fields = [
        "image_count",
        "modality",
        "image_metadata",
    ]

    for field in list_fields:
        values = parse_maybe_list(source_case.get(field))
        if values:
            metadata[field] = values

    for field in scalar_fields:
        value = source_case.get(field)
        if value not in (None, "", [], {}):
            metadata[field] = value

    return metadata


def to_raw_train_row(
    case_record: Dict,
    source_record_path: Path,
    case_text_result: CaseTextBuildResult,
    images: List[Dict[str, str]],
    source_image_metadata: Dict[str, Any],
) -> Dict:
    case_id = case_record["case_id"]
    article_id = case_record.get("article_id") or case_id.rsplit("_", 1)[0]
    diagnosis = build_diag_name(case_record)

    return {
        "case_id": case_id,
        "article_id": article_id,
        "leish_type": "Non-Leishmaniasis",
        "is_leishmaniasis": False,
        "diagnosis": diagnosis,
        "diagnosis_type": "Non-Leishmaniasis",
        "species": "",
        "case_text": case_text_result.text,
        "title": case_record.get("title", ""),
        "abstract": case_record.get("abstract", ""),
        "images": images,
        "journal": case_record.get("journal", ""),
        "year": case_record.get("year", ""),
        "doi": case_record.get("doi", ""),
        "license": case_record.get("license", ""),
        "pmcid": case_record.get("pmcid", article_id),
        "pmid": case_record.get("pmid", ""),
        "age": case_record.get("age"),
        "gender": case_record.get("gender", "Unknown"),
        "keywords": case_record.get("keywords", []),
        "mesh_terms": case_record.get("mesh_terms", []),
        "rag_is_split_child": False,
        "rag_parent_case_id": case_id,
        "rag_split_index": 1,
        "rag_split_total": 1,
        "labels": {
            "verified": {
                "diagnosis": diagnosis,
                "diagnosis_type": "Non-Leishmaniasis",
                "species": "",
                "is_leishmaniasis": False,
            },
            "pseudolabel": {
                "diagnosis": diagnosis,
                "diagnosis_type": "Non-Leishmaniasis",
                "species": "",
                "is_leishmaniasis": False,
            },
        },
        "source_case_record": str(source_record_path),
        "source_image_metadata": source_image_metadata,
        "case_text_builder": {
            "strategy": "richtext_v2",
            "estimated_tokens": case_text_result.estimated_tokens,
            "sections": case_text_result.sections,
        },
    }


def to_normalized_row(
    case_record: Dict,
    source_record_path: Path,
    phase_name: str,
    case_text_result: CaseTextBuildResult,
    images: List[Dict[str, str]],
    query_image_paths: List[str],
    image_audit: Dict[str, Any],
    source_image_metadata: Dict[str, Any],
) -> Dict:
    case_id = case_record["case_id"]
    article_id = case_record.get("article_id") or case_id.rsplit("_", 1)[0]
    diagnosis = build_diag_name(case_record)

    return {
        "case_id": case_id,
        "article_id": article_id,
        "case_text": case_text_result.text,
        "images": images,
        "diagnosis": diagnosis,
        "diagnosis_type": "Non-Leishmaniasis",
        "species": "",
        "is_leishmaniasis": False,
        "labels": {
            "verified": {
                "diagnosis": diagnosis,
                "diagnosis_type": "Non-Leishmaniasis",
                "species": "",
                "is_leishmaniasis": False,
            },
            "pseudolabel": {
                "diagnosis": diagnosis,
                "diagnosis_type": "Non-Leishmaniasis",
                "species": "",
                "is_leishmaniasis": False,
            },
        },
        "query_image_paths": query_image_paths,
        "split": f"train_{phase_name}",
        "source_jsonl": str(source_record_path),
        "reference_label": {
            "diagnosis": diagnosis,
            "diagnosis_type": "Non-Leishmaniasis",
            "species": "",
            "is_leishmaniasis": False,
            "provenance": "nonleish_case_records_pseudolabel",
            "clinician_validated": False,
            "is_ground_truth": False,
        },
        "pipeline_metadata": {
            "selection_phase": phase_name,
            "prompt1_model_id": case_record.get("prompt1_model_id", ""),
            "prompt2_model_id": case_record.get("prompt2_model_id", ""),
            "prompt2_quality_pass": bool(case_record.get("prompt2_quality_pass", False)),
            "inventory_image_count": int(case_record.get("inventory_image_count", 0) or 0),
            "image_linkage": image_audit,
            "source_image_metadata": source_image_metadata,
            "case_text_builder": {
                "strategy": "richtext_v2",
                "estimated_tokens": case_text_result.estimated_tokens,
                "sections": case_text_result.sections,
            },
        },
    }


def load_case_record(case_records_dir: Path, case_id: str) -> Tuple[Path, Dict]:
    path = case_records_dir / f"{case_id}.json"
    if not path.exists():
        raise FileNotFoundError(str(path))
    with open(path, "r", encoding="utf-8") as f:
        row = json.load(f)
    if str(row.get("case_id", "")).upper() != case_id:
        raise ValueError(f"Case ID mismatch in {path}: expected {case_id}, got {row.get('case_id')}")
    return path, row


def main() -> None:
    parser = argparse.ArgumentParser(description="Build non-leish train variants from selected case IDs")
    parser.add_argument("--phase-name", required=True, help="Name suffix for output artifacts, e.g. phase1a_tierA")
    parser.add_argument("--case-list", required=True, type=Path, help="Text file with one case_id per line")
    parser.add_argument(
        "--case-records-dir",
        type=Path,
        default=Path(
            "/home/ngocnt/Leishmania_v3/data/Infectious_disease_v2/"
            "classified_medgemma_27b_multimodal_fresh1_recovered_prompt12_stage_backfill_unified6208/case_records"
        ),
    )
    parser.add_argument(
        "--split-dir",
        type=Path,
        default=Path("/home/ngocnt/experiments/structured_cases_v4/leishmaniasis_verified_v2"),
    )
    parser.add_argument(
        "--source-candidates-jsonl",
        type=Path,
        default=Path("/home/ngocnt/Leishmania_v3/data/Infectious_disease_v2/infectious_candidates_cases.jsonl"),
        help="Source JSONL with case_image_files/case_image_captions fields",
    )
    parser.add_argument(
        "--classified-cases-jsonl",
        type=Path,
        default=Path(
            "/home/ngocnt/Leishmania_v3/data/Infectious_disease_v2/"
            "classified_medgemma_27b_multimodal_fresh1_recovered_prompt12_stage_backfill_unified6208/classified_cases.jsonl"
        ),
        help="Source JSONL for structured case text and pseudolabel mappings",
    )
    parser.add_argument(
        "--image-inventory-csv",
        type=Path,
        default=Path("/home/ngocnt/Leishmania_v3/data/Infectious_disease_v2/aligned_case_images/image_inventory.csv"),
        help="Aligned image inventory CSV",
    )
    parser.add_argument(
        "--aligned-images-root",
        type=Path,
        default=Path("/home/ngocnt/Leishmania_v3/data/Infectious_disease_v2/aligned_case_images"),
        help="Root folder with aligned case images",
    )
    parser.add_argument(
        "--images-target-root",
        type=Path,
        default=Path("/home/ngocnt/Leishmania_v3/data/leishmaniasis_multimodal/images"),
        help="Target root for train image files expected by indexer",
    )
    parser.add_argument(
        "--materialize-images",
        action="store_true",
        help="Copy/symlink linked images into images-target-root and populate query_image_paths",
    )
    parser.add_argument("--fail-on-missing", action="store_true", help="Stop if any case record is missing")
    args = parser.parse_args()

    split_dir = args.split_dir
    base_train_raw = split_dir / "train.jsonl"
    base_train_normalized = split_dir / "train_pseudolabel_v2_normalized.jsonl"
    test_raw = split_dir / "test.jsonl"
    test_normalized = split_dir / "test_pseudolabel_v2_normalized.jsonl"

    output_dir = split_dir / "nonleish_additions" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    requested_ids = read_case_ids(args.case_list)
    source_candidates = load_source_candidates(args.source_candidates_jsonl)
    classified_cases = load_classified_cases(args.classified_cases_jsonl)
    inventory_by_case_id, inventory_by_article_id = load_image_inventory(args.image_inventory_csv)

    train_raw_rows = read_jsonl(base_train_raw)
    train_norm_rows = read_jsonl(base_train_normalized)
    test_raw_rows = read_jsonl(test_raw)
    test_norm_rows = read_jsonl(test_normalized)

    train_ids = {str(r.get("case_id", "")).upper() for r in train_raw_rows} | {
        str(r.get("case_id", "")).upper() for r in train_norm_rows
    }
    test_ids = {str(r.get("case_id", "")).upper() for r in test_raw_rows} | {
        str(r.get("case_id", "")).upper() for r in test_norm_rows
    }

    missing_ids: List[str] = []
    collision_train_ids: List[str] = []
    collision_test_ids: List[str] = []
    added_rows_raw: List[Dict] = []
    added_rows_norm: List[Dict] = []
    image_audit: Dict[str, Dict[str, Any]] = {}

    for case_id in requested_ids:
        if case_id in train_ids:
            collision_train_ids.append(case_id)
            continue
        if case_id in test_ids:
            collision_test_ids.append(case_id)
            continue

        try:
            source_path, case_record = load_case_record(args.case_records_dir, case_id)
        except FileNotFoundError:
            if case_id in classified_cases:
                source_path = args.classified_cases_jsonl
                case_record = classified_cases[case_id]
            else:
                missing_ids.append(case_id)
                if args.fail_on_missing:
                    raise
                continue

        case_record = merge_non_empty_fields(classified_cases.get(case_id, {}), case_record)

        source_case = source_candidates.get(case_id, {})
        article_id = str(case_record.get("article_id") or case_id.rsplit("_", 1)[0]).upper()
        source_image_metadata = extract_source_image_metadata(source_case)
        images, query_image_paths, audit = build_images_from_source(
            case_id=case_id,
            article_id=article_id,
            source_case=source_case,
            inventory_by_case_id=inventory_by_case_id,
            inventory_by_article_id=inventory_by_article_id,
            aligned_images_root=args.aligned_images_root,
            materialize_images=args.materialize_images,
            images_target_root=args.images_target_root,
        )
        image_audit[case_id] = audit
        case_text_result = build_case_text(case_record, source_case)

        added_rows_raw.append(
            to_raw_train_row(case_record, source_path, case_text_result, images, source_image_metadata)
        )
        added_rows_norm.append(
            to_normalized_row(
                case_record,
                source_path,
                args.phase_name,
                case_text_result,
                images,
                query_image_paths,
                audit,
                source_image_metadata,
            )
        )

    merged_raw = train_raw_rows + added_rows_raw
    merged_norm = train_norm_rows + added_rows_norm

    base_norm_by_case_id = {str(row.get("case_id", "")).upper(): row for row in train_norm_rows}
    merged_norm_by_case_id = {str(row.get("case_id", "")).upper(): row for row in merged_norm}
    missing_existing_case_ids = sorted(set(base_norm_by_case_id) - set(merged_norm_by_case_id))
    changed_existing_case_ids = sorted(
        case_id
        for case_id, row in base_norm_by_case_id.items()
        if case_id in merged_norm_by_case_id and merged_norm_by_case_id[case_id] != row
    )

    raw_out = output_dir / f"train_{args.phase_name}.jsonl"
    norm_out = output_dir / f"train_pseudolabel_v2_{args.phase_name}.jsonl"
    manifest_out = output_dir / f"merge_manifest_{args.phase_name}.json"
    validation_out = output_dir / f"merge_validation_{args.phase_name}.json"

    write_jsonl(raw_out, merged_raw)
    write_jsonl(norm_out, merged_norm)

    stats = MergeStats(
        phase_name=args.phase_name,
        requested_case_count=len(requested_ids),
        unique_requested_case_count=len(requested_ids),
        added_case_count=len(added_rows_raw),
        missing_case_count=len(missing_ids),
        collision_train_count=len(collision_train_ids),
        collision_test_count=len(collision_test_ids),
    )

    manifest = {
        "phase_name": args.phase_name,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "case_list_file": str(args.case_list),
        "case_records_dir": str(args.case_records_dir),
        "classified_cases_jsonl": str(args.classified_cases_jsonl),
        "selected_case_ids": requested_ids,
        "added_case_ids": [row["case_id"] for row in added_rows_raw],
        "image_audit_by_case": image_audit,
        "missing_case_ids": missing_ids,
        "collision_train_case_ids": collision_train_ids,
        "collision_test_case_ids": collision_test_ids,
        "outputs": {
            "train_raw": str(raw_out),
            "train_pseudolabel_v2": str(norm_out),
        },
    }

    validation = {
        "stats": stats.__dict__,
        "base_counts": {
            "train_raw": len(train_raw_rows),
            "train_pseudolabel_v2": len(train_norm_rows),
            "test_raw": len(test_raw_rows),
            "test_pseudolabel_v2": len(test_norm_rows),
        },
        "result_counts": {
            "train_raw": len(merged_raw),
            "train_pseudolabel_v2": len(merged_norm),
        },
        "consistency": {
            "added_raw_equals_added_norm": len(added_rows_raw) == len(added_rows_norm),
            "all_added_non_leish": all(not row["is_leishmaniasis"] for row in added_rows_raw),
            "all_added_case_ids_unique": len({row["case_id"] for row in added_rows_raw}) == len(added_rows_raw),
            "added_with_images": sum(1 for row in added_rows_norm if row.get("images")),
            "added_with_query_image_paths": sum(1 for row in added_rows_norm if row.get("query_image_paths")),
            "baseline_rows_preserved": len(missing_existing_case_ids) == 0 and len(changed_existing_case_ids) == 0,
            "baseline_missing_case_count": len(missing_existing_case_ids),
            "baseline_changed_case_count": len(changed_existing_case_ids),
        },
        "baseline_preservation": {
            "missing_case_ids": missing_existing_case_ids,
            "changed_case_ids": changed_existing_case_ids,
        },
    }

    with open(manifest_out, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    with open(validation_out, "w", encoding="utf-8") as f:
        json.dump(validation, f, indent=2)

    print("=== Non-Leish Train Variant Build ===")
    print(f"phase_name={args.phase_name}")
    print(f"requested={len(requested_ids)}")
    print(f"added={len(added_rows_raw)}")
    print(f"missing={len(missing_ids)}")
    print(f"collision_train={len(collision_train_ids)}")
    print(f"collision_test={len(collision_test_ids)}")
    print(f"added_with_images={sum(1 for row in added_rows_norm if row.get('images'))}")
    print(f"materialize_images={bool(args.materialize_images)}")
    print(f"output_train_raw={raw_out}")
    print(f"output_train_pseudolabel_v2={norm_out}")
    print(f"validation={validation_out}")


if __name__ == "__main__":
    main()
